# Generated by Django 3.2.8 on 2021-11-29 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20211129_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='followers',
        ),
        migrations.AddField(
            model_name='person',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='person_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='person',
            name='following',
        ),
        migrations.AddField(
            model_name='person',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='person_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
