# Generated by Django 3.2.8 on 2021-11-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211130_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='posts',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
