# Generated by Django 3.2.8 on 2021-12-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20211130_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
