# Generated by Django 3.2.8 on 2021-12-11 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20211210_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='network.user'),
            preserve_default=False,
        ),
    ]
