# Generated by Django 3.2.8 on 2021-12-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
