# Generated by Django 3.2.8 on 2021-12-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-creation']},
        ),
    ]
